### PR TITLE
Fix build issues and update references

### LINKED ISSUE #37: Need to update references in QBitNinja
There is old references to VS2015 elements in here so on a machine with only VS2017 installed the project can't be built.

### PR DESCRIPTION
**Pull request by mikedennis**
This should fix #37 as well as updates the reference to azure storage and update other nuget packages to more modern versions. Also targets the same .net framework for each of the projects.

### CODE REVIEW

**Comment by YakupIpek** [comment]
@mikedennis Currently QBitNinja.Tests project doesnt compile. Can you please take a look at it ?

**Comment by mikedennis** [comment]
@YakupIpek It compiles successfully for me. What error are you getting?

**Comment by mikedennis** [comment]
I believe issue is missing hintpath's in csproj. I will correct those.

**Comment by bokobza** [comment]
Can this be updated? @YakupIpek @mikedennis

**Comment by bokobza** [comment]
Thanks @mikedennis !

**Pull request merged**
